language: java
before_install:
- .travis/check_branch.sh
env:
  global:
  - secure: FOCi/L0glQHZbWt6tkRHZaYj6I32CQtHm9/abQpYNBQlusol6NQLtfO5/YcOR0kHYM9kQUKCGcHbFXEN8YGMtO+R+ob4Hz5VuGZgtAa6wcAUCL7+jaBRDmEEnLNRX991MmEKAxX2Ect0LAGtLzYytjTuZt4R7XTkeILRG6dRNjWdkXW+MdkxKtEGIknrRlC5kPGXW6fMZVyTB4EYHXSaCrH2CrExQu9yavWLxBTNGteT6rKwAExzrr74yUxxYY/DkTfsRLjb4FIkM++ulN/gwmytjxv1Wx3qPSgvv/ja0j8E3qxQwIs6jBTdUX6I5ibnL9VrlEpFC4R/zsQ82ow8Wv+cB8vK4fYUBrJKjnAdguWrYWBqrLj2dQcRbtLS8DubeDLGGF+9Yc8VarGrCjR0j49XSY25PDkletxztPdHDtYPAClou2orSc7BlxVYFoKHa+1SUgwEUUwYpfyRpRxoryDR3a/cylDFfXpGVZONbyTZzxbronvUcRos17uJ34GMKlJU4DtBsML98/9bBEwNThroeuPfbrXEpSZstQRfm378QjWhkFrzJYzwJLp0nVhqLskiQx1VGhcrKrefcNQaCA0tcTIlYeCy8mZGKwhp4vAgxKsbE8aUuUM02qjnOAd3L+IY4NAww9SSWoxUCgiOVe2L+nImJKy39ZvGsZ1nhVE=
  - secure: cTArKxSFC0oYy0PXtFTvMI5IG+T+9wVEHMpx59c2OAvjeOMZh4ppe0NlU5pO98uDboGXxMCi0zHzmVmS4apoYWD/eMGDyGb5YHnjggTWJmLpLEHafnQYXMfBKHNPRGdKUMVWh1p+2O/6RK3YrViE7J0S54irrHd+zZS7DQeqWVqq6J82WoF33Vi9aTj++zP1NLXuFrWW1bTxt81/P63Re7S3n3+j1vPQ6hP87eNZ/WBnshw438KrDbFd/L7dCsXagz3ynMdwi7PJkr4khHb57R0HmUjOTl/qTAlEc+Ik2gEVWkf6XNGUe+I9rvTlh8ZDk7M0x46VH6LYbprFVnV4+2z0V7ikWznB7T15Z7rCcLMoI7ACiB+HuIhuzIqovrPYJ2OYWq28T6iCFdlBU9V6G7dggGjPf/QogDerlYVjn62uR16zQM8j0c1grW7ziRMtzdLpsUPxjPdOBvL/wxnFfGB/H/jYMGa1XwhND9Wx3P2yR4FXkl0EorkNHzI3El7iWUoWVFfLLYnjOoMiGXDJ1pdNPFYEmpOQJ9uX+KcrxoTDnnbH84bY7fD2FX/OIm7d4jZuqqfGw/gwlJlYkUGH/O9aAcaw4DObdOXb0phsrGzMB/KGSlDZ5XsYAwCOQ5hLQ7k93l/CLFfkdsNBSl/ZyzlI/QPEgr9MWkIgFRmMe98=
  - secure: M9658Jx99QXJMq3a096ob6t6HI2qUnguCFAi8138mAocTdKPGG6eBu/NnkNQ4MeeIyh+sumGdEgLxzVsKCsTQloRO699PVe2yPwY2VAxaCLxvOM9qoMBGUxKl5/FEDU3NWqTxZ7kXALmwPP66ldMomslkod2YhhjmCD0I+cDEGa8+PBPefrDnxSE8JOaFVgoHPQYSlEas0m5doRnIqRacR88JM8lIGgA5FY4rwPuN1aRNbJj1oYo6KBV2I+zkJ8rC1yv6g6nTYwudAUKdk0wXurnhi05CH/bzHHD3NvjRGGZZW/TFWNa0gysSqka0xuYW3pPExPXWBxut0CrDlnm8Vsm0WHQ/+cfGwRRz9ojUIWLHrtbcwoC8MWM/2krM0v76PyGwlQgWSwJxEjr8VkFK0lUpuM/ayWgQIZudMoE4cENY8R5OeFc29f/6RPYrnqF2vNxaeVBijx6Z5HgYyyDGs2eNq4UaagPfUg8rgkpRlvKbq0mejVSbTzqGv8io0pbl++QMZZ/1TnU+XOy0o6FUzL0cOOdDP0DJSbEzlw7LyrbgJ1AMe8e92gB9IxK6VPZThKswoUgxOPn+aazcpqk8oa4EUyqFD888jbSdsCgZspyPKuUyNrYPMbu5YE+AFDFlky9w0ggWFy8gkLoK0/ZULuJUUXppQgHWL0TCTME/mY=
  - secure: Dxvb3ouy2eUxQAk6RvyPABdQnPRN/d+4fVgWDwki/iL0Ztosuy3TykUK7ai9z5cF3mwXBaVkFgesS4B6pxKevbmzvO2wg7Lu9mI7/9hBT1w1M8GkhvaI1v7vuR2MAMkLDzzHghzf8LwiLioEuA9Wa62BCh7jZBCqJoe6bctD6BG2YSyezd/MXMp7OF6Ii+9V4u04Q3nAn8IZfu9ccZ7z1OQBD2tef2IDB3/azlWUnyhOUvHyGORqn/0IL8HxD/r5byMaqBemg9yjNW+K2XKXtf32G7TyVHCvOLBpujdMrvQlgVi1czmgo4UV/hJYB7elZLmwRdlIXD+J5L5zJdUOJ9rlO0bwaMdltLWTnrEjZpXOhRhe/k2tUP4LFaJa8tArlsikEH9T1bHgUXRzs15jjdB97o8XSsYdpIOBont/q+85K5IugbYEazZc2W0AFLGqtYjJI/W8TKOuJVX031+3vLdGCuJacK/VpwOUC4S6VfeU1bvCeWemKybvaY2dJj02TQaZ16YyIHJbheep12gqStP6Fk+i6P4HhMKceLEZAsXtGWrEd6QPM3VDzGyJJZMzZA7BWdJnZR+Dq9Sva/eYnX7nFrgJPwZRI754f4L9RK4LqtulogZO+5kxQki++NaolphVmg0mJU00E1GSLYHAQSlAZBwMsenI7v10ZbUW5Q0=
  - secure: iY5t9EbZ+3B2Nfw5LwGn9NBqOL60/eKZW1zss5Ba/CqaHQl0tiigp7Sll4Ybh5TX+RCICjN9SelcDdj372sFtq/9Zm24NI/0WHaZhsPeIZNimSgjzTm/24Vv2LhQ1FjOk+uXeZuJ7LQOH2ldB7RwxtlYAD67SiRPMncl0Njp9CMRHyUKqOZuTNrUe6bL7uvA0MFGFHVdkjVmUwNVjEquhoEdJ2l3kKS7sv6DemNg51rpxfHFouU+t+A+K4L5yn0GNTIrMcrQqc3EN0iy9k+5gc1cZ7XaDItvX6PVSjShAmBKleAf19IHYevE6s0Bjiyh7CeuwRoMlXQ4xs8duT5c/1pz36XM00v+Mlav6iEXDwlggB0qRDENCS40uuCapfhsumimHrqkBa4FcPVkU5VbBYYdSAkqdh06C3An5CpUkSw9z5Z6dMaJjmODtrQGwbULGQL4NBxA+Dm+Z5UoZBL52OJlatfFSbZ5bYh401ZkQdcQmXuXYj3UPEZ9Jw9ERNYN6Q+2whQ57hEOai3pFGp44ZrgGfaMBgB77dfoxe/IDUQR/6nswnR3+CHstzLcTan7X8TpzfKKE751KqZGkb+K0QXvygUHzWfqxKyeJazKB5F4FQ0L36AAPSg7GsipookOQ5yEM57ZEIirVDhxdYwWRZ/e9jOYFUUnzFtPW+ooi/Y=
jobs:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
    - stage: deploy_dev
      if: branch = develop AND type = cron
      before_install:
        - echo "$GPG_SECRET_KEYS" | base64 --decode | $GPG_EXECUTABLE --import
        - echo "$GPG_OWNERTRUST" | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - .travis/set_ssh.sh
        - git remote set-url origin git@github.com:bsc-dom/javaclay.git
      deploy:
          provider: script
          script: mvn -P publish deploy -s settings.xml
          on:
               branch: develop
    - stage: deploy_release 
      if: branch = master AND type != pull_request AND commit_message != "New release"
      before_install:
        - echo "$GPG_SECRET_KEYS" | base64 --decode | $GPG_EXECUTABLE --import
        - echo "$GPG_OWNERTRUST" | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - .travis/set_ssh.sh
        - git remote set-url origin git@github.com:bsc-dom/javaclay.git
      deploy:
          provider: script
          script: mvn -q -P publish -B release:clean release:prepare release:perform -s settings.xml
          on:
               branch: master
      after_deploy:
        - .travis/new_version.sh
notifications:
  email:
    - commiter:
      on_success: change
      on_failure: always
    - cron:
      if: type = cron
      recipients:
        - support-dataclay@bsc.es
      on_success: change
      on_failure: always