
package es.bsc.dataclay.util.management.metadataservice;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import es.bsc.dataclay.util.ids.DataClayInstanceID;

public class DataClayInstance {
	/** ID generated by source dataClay instance. */
	private DataClayInstanceID dcID;
	/** Host of the main service of the dataClay instance. */
	private List<String> hosts;
	/** Port of the main service of the dataClay instance. */
	private List<Integer> ports;

	/**
	 * Empty constructor of the DataClayInstance
	 */
	public DataClayInstance() {
	}

	public DataClayInstance(final DataClayInstanceID newdcID, final String newhost, final Integer newport) {
		this.dcID = newdcID;
		this.hosts = Collections.synchronizedList(Arrays.asList(new String[]{newhost}));
		this.ports = Collections.synchronizedList(Arrays.asList(new Integer[]{newport}));
	}

	/**
	 * Basic constructor for dataClay instances. For each host must be a port.
	 * 
	 * @param newdcID
	 *            id of the dataClay instance
	 * @param newhosts
	 *            hosts of the main service of the dataClay instance
	 * @param newports
	 *            ports of the main service of the dataClay instance
	 */
	public DataClayInstance(final DataClayInstanceID newdcID, final String[] newhosts, final Integer[] newports) {
		this.dcID = newdcID;
		this.hosts = Collections.synchronizedList(Arrays.asList(newhosts));
		this.ports = Collections.synchronizedList(Arrays.asList(newports));
	}

	public DataClayInstanceID getDcID() {
		return dcID;
	}

	public void setDcID(final DataClayInstanceID newdcID) {
		this.dcID = newdcID;
	}

	public List<String> getHosts() {
		return hosts;
	}

	public void setHosts(final List<String> hosts) {
		this.hosts = hosts;
	}

	public List<Integer> getPorts() {
		return ports;
	}

	public void setPorts(final List<Integer> ports) {
		this.ports = ports;
	}

	@Override
	public String toString() {
		return "DataClay instance info: [id: " + getDcID() + "] [hosts: "
				+ hosts
				+ "] [corresponding ports: " + ports + "]";
	}
}
